language: node_js
node_js:
  - 8
script: echo $TEST
env:
  - TEST=BLAH

    # language: node_js
    # node_js:
    # - "stable"
    # script: gulp travis
    # env:
    # - NODE_ENV="development"
    # services:
    # - mongodb
